[package]
name = "first_rs_engine"
version = "0.1.0"
authors = ["Siebencorgie <siebencorgie@googlemail.com>"]

[dependencies]
gfx = "0.15"
glutin = "0.8"
gfx_window_glutin = "0.16"
cgmath = "0.14.1"
image = "*"
time = "*"
gfx_device_gl = "0.14"
assimp = "0.2.0"
ears = "0.4.0"
